spring.application.name=finance-tracker
server.port=1234

spring.datasource.url=jdbc:postgresql://db.hvnxwrggidxzrmerzqig.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=GUtUPc732I4DD2nX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate